DietApp/Models/Recipe.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DietApp.Models
{
    public class Recipe
    {
        [HiddenInput(DisplayValue = false)]
        public int RecipeId { get; set; }
        [Display(Name = "Użytkownik")]
        public string UserId { get; set; }

        [Required(ErrorMessage = "Nazwa przepisu jest wymagana!")]
        [MaxLength(50, ErrorMessage = "Nazwa może mieć maksymalnie 50 znaków")]
        [Display(Name = "Nazwa przepisu")]
        public string Title { get; set; }
        public string ImageName { get; set; }
        [NotMapped]
        [Display(Name = "Zdjęcie przepisu")]
        public IFormFile Image { get; set; }

        [Required(ErrorMessage = "Opis przepisu jest wymagany!")]
        [MaxLength(5000, ErrorMessage = "Opis może mieć maksymalnie 5000 znaków")]
        [Display(Name = "Opis przepisu")]
        public string Description { get; set; }

        [Required(ErrorMessage = "Wybierz poziom trudności!")]
        [Display(Name = "Poziom trudności")]
        [EnumDataType(typeof(Difficulty))]
        public Difficulty DifficultyLevel { get; set; }

        [Required(ErrorMessage = "Czas przygotowania jest wymagany!")]
        [Display(Name = "Czas przygotowania")]
        [Range(1, int.MaxValue, ErrorMessage = "{0} musi być większy niż 0.")]
        public int PreparationTime { get; set; }

        [Required(ErrorMessage = "Liczba porcji jest wymagany!")]
        [Display(Name = "Liczba porcji")]
        [Range(1, int.MaxValue, ErrorMessage = "{0} musi być większa niż 0.")]
        public int Portions { get; set; }
        public double TotalKcal { get; set; }
        public double TotalFat { get; set; }
        public double TotalCarbo { get; set; }
        public double TotalProtein { get; set; }
        public int TotalWeight { get; set; }

        public virtual ApplicationUser User { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
        [Display(Name = "Kategorie")]
        public virtual ICollection<Category> Category { get; set; }
        public virtual ICollection<RecipeIngredient> Ingredients { get; set; }

        public enum Difficulty
        {
            [Display(Name = "Bardzo łatwy")]
            VeryEasy =1,
            [Display(Name = "łatwy")]
            Easy =2,
            [Display(Name = "Średni")]
            Medium =3,
            [Display(Name = "Trudny")]
            Hard =4,
            [Display(Name = "Bardzo trudny")]
            VeryHard =5
        }
    }
}

DietApp/Controllers/RecipesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DietApp.Data;
using DietApp.Models;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;
using NuGet.ContentModel;
using static System.Net.WebRequestMethods;
using System.Reflection.Metadata;
using Microsoft.Extensions.Hosting;
using System.Globalization;
using NuGet.Packaging;

namespace DietApp.Controllers
{
    public class RecipesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment _hostEnvironment;

        public RecipesController(ApplicationDbContext context, IWebHostEnvironment hostEnvironment)
        {
            _context = context;
            _hostEnvironment = hostEnvironment;
        }

        // GET: Recipes
        public async Task<IActionResult> Index(string search, string currentFilter, int? pageNumber, string category)
        {
            ViewBag.Categories = _context.Categories;
            if (search != null)
            {
                pageNumber = 1;
            }
            else
            {
                search = currentFilter;
            }
            ViewData["CurrentFilter"] = search;
            ViewData["CurrentCategory"] = category;
            var recipes = await _context.Recipes.Include(r => r.User).Include(r => r.Category).ToListAsync();
            if (!String.IsNullOrEmpty(search))
            {
                recipes = recipes.Where(r => r.Title.Contains(search, StringComparison.OrdinalIgnoreCase)).ToList();
            }
            if (!String.IsNullOrEmpty(category))
            {
                var cat = _context.Categories.FirstOrDefault(c => c.Name.Equals(category));
                recipes = recipes.Where(r => r.Category.Any(i => i.CategoryId == cat.CategoryId) == true).ToList();
            }

            int pageSize = 10;
            return View(PaginatedList<Recipe>.Create(recipes, pageNumber ?? 1, pageSize));
        }

        // GET: Recipes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Recipes == null)
            {
                return NotFound();
            }
            ViewBag.RecipeId = id;
            var recipe = await _context.Recipes
                .Include(r => r.User)
                .Include(r => r.Comments)
                    .ThenInclude(c => c.User)
                .Include(r => r.Ingredients)
                    .ThenInclude(i => i.Product)
                .Include(r => r.Category)
                .FirstOrDefaultAsync(m => m.RecipeId == id);
            if (recipe == null)
            {
                return NotFound();
            }
            ViewBag.CommentsCount = recipe.Comments.Count();
            if(ViewBag.CommentsCount == 0)
            {
                ViewBag.Rating = 0;
            }
            else
            {
                double rating = 0.0;
                foreach (var comment in recipe.Comments)
                {
                    rating += comment.Rating;
                }
                NumberFormatInfo nfi = new()
                {
                    NumberDecimalSeparator = "."
                };
                ViewBag.Rating = (Math.Round(rating / ViewBag.CommentsCount, 1)).ToString(nfi); ;
            }
            return View(recipe);
        }

        // GET: Recipes/Create
        [Authorize]
        public IActionResult Create()
        {
            ViewData["Products"] = new SelectList(_context.Products, "ProductId", "Name");
            ViewData["Categories"] = new SelectList(_context.Categories, "CategoryId", "Name");
            return View();
        }

        // POST: Recipes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("RecipeId,Title,Image,Description,DifficultyLevel,PreparationTime,Portions,Ingredients")] Recipe recipe, int[] categoriesId)
        {
            if (ModelState.IsValid)
            {
                if (recipe.Image != null)
                {
                    string wwwRootPath = _hostEnvironment.WebRootPath;
                    string fileName = Path.GetFileNameWithoutExtension(recipe.Image.FileName);
                    string extension = Path.GetExtension(recipe.Image.FileName);
                    fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
                    recipe.ImageName = fileName;
                    string path = Path.Combine(wwwRootPath + "/images/", fileName);
                    if (!Directory.Exists(path))
                    {
                        Directory.CreateDirectory(wwwRootPath + "/images/");
                    }
                    path = Path.Combine(wwwRootPath + "/images/", fileName);
                    using var fileStream = new FileStream(path, FileMode.Create);
                    await recipe.Image.CopyToAsync(fileStream);
                }
                var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
                recipe.UserId = userId;
                double totalKcal = 0;
                double totalFat = 0;
                double totalCarbo = 0;
                double totalProtein = 0;
                int totalWeight = 0;
                foreach (var item in recipe.Ingredients)
                {
                    totalKcal += _context.Products.Find(item.ProductId).KcalPer100 * item.Weight/100;
                    totalFat += _context.Products.Find(item.ProductId).FatPer100 * item.Weight / 100;
                    totalCarbo += _context.Products.Find(item.ProductId).CarboPer100 * item.Weight / 100;
                    totalProtein += _context.Products.Find(item.ProductId).ProteinPer100 * item.Weight / 100;
                    totalWeight += item.Weight;
                    using (var transaction = _context.Database.BeginTransaction())
                    {
                        _context.Database.ExecuteSqlRaw("SET IDENTITY_INSERT dbo.RecipeIngredients ON;");
                        _context.Add(item);
                        transaction.Commit();
                    }
                }
                List<Category> categories = new(); 
                foreach (var item in categoriesId)
                {
                    Category category = _context.Categories.Find(item);
                    categories.Add(category);
                }
                recipe.Category = categories;
                recipe.TotalKcal = Math.Round(totalKcal, 2);
                recipe.TotalFat = Math.Round(totalFat, 2);
                recipe.TotalCarbo = Math.Round(totalCarbo, 2);
                recipe.TotalProtein = Math.Round(totalProtein, 2);
                recipe.TotalWeight = totalWeight;                
                _context.Add(recipe);
                await _context.SaveChangesAsync();

                Product product = new();
                product.Name = recipe.Title;
                product.KcalPer100 = Math.Round(recipe.TotalKcal / recipe.TotalWeight * 100, 2);
                product.FatPer100 = Math.Round(recipe.TotalFat / recipe.TotalWeight * 100, 2);
                product.CarboPer100 = Math.Round(recipe.TotalCarbo / recipe.TotalWeight * 100, 2);
                product.ProteinPer100 = Math.Round(recipe.TotalProtein / recipe.TotalWeight * 100, 2);
                product.Image = recipe.Image;
                product.ImageName = recipe.ImageName;
                product.RecipeId = recipe.RecipeId;
                _context.Add(product);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["Products"] = new SelectList(_context.Products, "ProductId", "Name");
            ViewData["Categories"] = new SelectList(_context.Categories, "CategoryId", "Name");
            return View(recipe);
        }

        // GET: Recipes/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Recipes == null)
            {
                return NotFound();
            }

            var recipe = await _context.Recipes.FindAsync(id);
            if (recipe == null)
            {
                return NotFound();
            }
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "UserName", recipe.UserId);
            return View(recipe);
        }

        // POST: Recipes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("RecipeId,UserId,Title,Description,DifficultyLevel,PreparationTime,Portions,Ingredients")] Recipe recipe)
        {
            if (id != recipe.RecipeId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(recipe);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RecipeExists(recipe.RecipeId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }

DietApp/Views/Recipes/Create.cshtml
@model DietApp.Models.Recipe

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div style="max-width: 80%; margin-left:10%">
    <p class="display-6">Dodaj przepis</p>
    <hr />
    <div class="text-center">
        <div>
            <form asp-action="Create" method="post" enctype="multipart/form-data">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Title" class="control-label"></label>
                    <input asp-for="Title" class="form-control" />
                    <span asp-validation-for="Title" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Description" class="control-label"></label>
                    <textarea rows="6" asp-for="Description" class="form-control"></textarea>
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Category" class="control-label"></label>
                    <select asp-for="Category" name="categoriesId" class="form-control" multiple>
                    @foreach(var item in ViewBag.Categories)
                    {
                        <option value=@item.Value>@item.Text</option>
                    }
                    </select>
                    <span asp-validation-for="Category" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="DifficultyLevel" class="control-label"></label>
                    <select asp-for="DifficultyLevel" class="form-select">
                        <option value="" selected>--Wybierz--</option>
                        <option value="VeryEasy">Bardzo łatwy</option>
                        <option value="Easy">Łatwy</option>
                        <option value="Medium">Średni</option>
                        <option value="Hard">Trudny</option>
                        <option value="VeryHard">Bardzo trudny</option>
                    </select>
                    <span asp-validation-for="DifficultyLevel" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="PreparationTime" class="control-label"></label>
                    <div class="input-group">
                        <input asp-for="PreparationTime" class="form-control" />
                        <span class="input-group-text"> min </span>
                    </div>
                    <span asp-validation-for="PreparationTime" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Portions" class="control-label"></label>
                    <input asp-for="Portions" class="form-control" />
                    <span asp-validation-for="Portions" class="text-danger"></span>
                </div>
            
                <div id="ingredientsTable">
                    <table>
                        <thead>
                            <tr>
                                <th>Produkt</th>
                                <th>Ilość</th>
                            </tr>
                        </thead>
                        <tbody id="ingredientsList" data-count="1">
                            <tr id="tr[0]">
                                <td>
                                    <select class="form-select" name="Ingredients[0].ProductId">
                                        <option value="" selected>--Wybierz--</option>
                                        @foreach (var item in ViewBag.Products)
                                        {
                                            <option value=@item.Value>@item.Text</option>
                                        }
                                    </select>
                                </td>
                               <td>
                                   <div class="input-group">
                                       <input type="text" name="Ingredients[0].Weight" class="form-control" required />
                                       <span class="input-group-text"> g </span>
                                   </div>
                               </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                <div style="padding-bottom:20px">
                    <button type="button" class="btn btn-primary" onclick="AddRow()">Dodaj składniki</button>
                </div>
                <div class="form-group">
                    <label asp-for="Image" class="control-label"></label>
                    <input asp-for="Image" accept="image/*" />
                    <span asp-validation-for="Image" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>


    <div>
        <a asp-action="Index">Back to List</a>
    </div>
</div>

<style>
    .close {
        cursor: pointer;
        position: absolute;
        top: 50%;
        right: 0%;
        padding: 12px 16px;
        transform: translate(0%, -50%);
    }
</style>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script>

          function AddRow()
          {
            var countVal = parseInt($('#ingredientsList').attr('data-count'));
            var html = '';
            html += '<tr id="tr[' + countVal + ']">';
            html += '   <td><select class="form-select" name="Ingredients[' + countVal + '].ProductId"><option value="" selected>--Wybierz--</option>@foreach (var item in ViewBag.Products){<option value=@item.Value>@item.Text</option>}</select></td>';
            html += '   <td><div class="input-group"><input type="text" name="Ingredients[' + countVal + '].Weight" class="form-control" required/><span class="input-group-text"> g </span></div></td>';
            html += '   <td data-close><span id="' + countVal + '" onclick="DeleteRow(this.id)" type="button" class="px-2 py-1">&times;</span></td > ';
            html += '</tr>';

            $('#ingredientsList').append(html);
              countVal += 1;
            $('#ingredientsList').attr('data-count', countVal);

          }
          function DeleteRow(id)
          {
              document.getElementById('tr[' + id + ']').style.display = 'none';
            console.log('tr[' + id + ']');
          }
    </script>
    
}

DietApp/Views/Recipes/Delete.cshtml
@model DietApp.Models.Recipe

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Recipe</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DifficultyLevel)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DifficultyLevel)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PreparationTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PreparationTime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Portions)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Portions)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TotalKcal)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TotalKcal)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TotalFat)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TotalFat)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TotalCarbo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TotalCarbo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TotalProtein)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TotalProtein)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TotalWeight)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TotalWeight)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.User)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.User.UserName)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="RecipeId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

DietApp/Views/Recipes/Details.cshtml
@model DietApp.Models.Recipe
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager


@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
    <link rel="stylesheet" href="https://cdn.korzh.com/metroui/v4.5.1/css/metro-all.min.css">
    <script src="https://cdn.korzh.com/metroui/v4.5.1/js/metro.min.js"></script>
}

<div class="p-3" style="max-width: 80%; margin-left:10%">
    <div style="height:50px">
        <div class="w-50" style="float:left">
            <input data-role="rating"
                   data-value="@ViewBag.Rating"
                   data-message="(@ViewBag.CommentsCount)"
                   data-static="true">
        </div>
        <div class="w-50 text-end" style="float:left">
            <p>@Model.User.UserName</p>
        </div>
    </div>
    <div class="text-center my-5">
        <p class="display-3 m-3">@Model.Title</p>
        @if (Model.ImageName != null)
        {
            <img decoding="async" src="@("~/images/"+Model.ImageName)" asp-append-version="true" width="400px" class="m-3" />
        }
        <div class="text-start">
            @if (Model.Category.Count() > 0)
            {
                <h5 class="mt-4">Kategorie:</h5>
                @foreach (var item in Model.Category)
                {
                    @item.Name

                    <text>, </text>
                }
            }
            <h5 class="mt-4">Składniki:</h5>
            <ul>
                @foreach(var item in Model.Ingredients)
                {
                    <li><b>@item.Product.Name: </b>@item.Weight g</li>
                }
            </ul>
            <h5 class="mt-4">Przepis:</h5>
            <p style="text-align: justify">@Model.Description</p>
        </div>
        <div class="text-start mt-4">
            <p><b>Czas przygotowania:</b> @Model.PreparationTime minut</p>
            <p><b>Liczba porcji:</b> @Model.Portions</p>
            <p><b>Wartość odżywcza:</b></p>
            <ul>
                <li>Kalorie: @Model.TotalKcal kcal</li>
                <li>Tłuszcz: @Model.TotalFat g</li>
                <li>Węglowodany: @Model.TotalCarbo g</li>
                <li>Białko: @Model.TotalProtein g</li>
            </ul>
        </div>
    </div>
    <div>
        <partial name="_AddComment" model="null"/>
    </div>
    <div class="pt-5">
        @if (Model.Comments.Count == 0)
        {
            <p>Brak komentarzy</p>
        }
        @foreach(var item in Model.Comments)
        {
            <div class="border rounded m-2 p-1" style="min-height:40px">
                <div class="w-50" style="float:left">
                    <b>@item.User.UserName</b>
                </div>
                <div class="text-end w-50" style="float:left">
                    <input data-role="rating"
                        data-value="@item.Rating"
                        data-static="true" />
                </div>
                <p>@item.Content</p>
                @if (SignInManager.IsSignedIn(User))
                {
                    @if (ViewContext.HttpContext.User.IsInRole("Admin") || UserManager.GetUserId(User) == item.UserId)
                    {
                        <div class="text-end">
                            <form asp-action="DeleteComment">
                                <input type="hidden" name="commentId" value="@item.CommentId" />
                                <input type="submit" value="Usuń" />
                            </form>
                        </div>
                    }
                }
            </div>
        }
    </div>
    <br />
    <br />
    <br />
</div>

DietApp/Views/Recipes/Edit.cshtml
@model DietApp.Models.Recipe

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>Recipe</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="RecipeId" />
            <div class="form-group">
                <label asp-for="UserId" class="control-label"></label>
                <select asp-for="UserId" class="form-control" asp-items="ViewBag.UserId"></select>
                <span asp-validation-for="UserId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DifficultyLevel" class="control-label"></label>
                <select asp-for="DifficultyLevel" class="form-select">
                    <option value="" selected>--Wybierz--</option>
                    <option value="VeryEasy">Bardzo łatwy</option>
                    <option value="Easy">Łatwy</option>
                    <option value="Medium">Średni</option>
                    <option value="Hard">Trudny</option>
                    <option value="VeryHard">Bardzo trudny</option>
                </select>
                <span asp-validation-for="DifficultyLevel" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PreparationTime" class="control-label"></label>
                <input asp-for="PreparationTime" class="form-control" />
                <span asp-validation-for="PreparationTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Portions" class="control-label"></label>
                <input asp-for="Portions" class="form-control" />
                <span asp-validation-for="Portions" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DietApp/Views/Recipes/_AddComment.cshtml
@model DietApp.Models.Comment

<hr />
<h3>Komentarze:</h3>
<form asp-controller="Recipes" asp-action="AddComment">
    <input asp-for="RecipeId" type="hidden" value="@ViewBag.RecipeId"/>
    <textarea asp-for="Content" name="content" placeholder="Komentarz" class="w-100 p-2" rows="4"></textarea>
    <span asp-validation-for="Content" class="text-danger"></span>
    <div>
        <input asp-for="Rating" data-role="rating" name="rating" data-values="1, 2, 3, 4, 5"  onchange="ActiveButton()" on>
        <span asp-validation-for="Rating" class="text-danger"></span>
    </div>
    <div class="text-end">
        <button type="submit" id="buttonId"  class="btn btn-dark" disabled>Dodaj komentarz</button>
    </div>
</form>

<script>
    function ActiveButton() {
        document.getElementById("buttonId").removeAttribute("disabled");
    }
</script>